[package]
name = "rust_gpu_shaders"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["dylib"]

[dependencies]
spirv-std = { git = "https://github.com/projectkml/rust-gpu", branch = "ext-mesh-shader" }